### ISSUE TITLE
npm run ios error

### ISSUE THREAD

**Issue by junwangInChina** [1280103995/react-native-elm#1]
![simulator screen shot - iphone 6 - 2018-04-26 at 14 23 05](https://user-images.githubusercontent.com/2849111/39289152-79979226-495d-11e8-887d-1cee42d54191.png)

done 到本地后
npm install 
npm install --save redux
npm install --save react-redux

之后 npm run ios or react-native run-ios, 都报这个错
ios unhandled js exception clould not get batchedbridge .make sure your bundle is packaged correctly
大神有没有时间看一下什么问题

类似问题网上找个几个解决方案，都没有效果

**Comment by 1280103995** [comment]
试试删除ios工程中的的build文件夹，然后 yarn
