### ISSUE TITLE
iOS项目运行在Xcode Version 11.4 (11E146)

### ISSUE THREAD

**Issue by inkCrazy** [1280103995/react-native-elm#10]
Showing All Messages

Build target elm of project elm with configuration Debug
error: /Users/inkcrazy/Desktop/elmProject/react-native-elm/ios/Pods/Pods/Target Support Files/Pods-elm/Pods-elm.debug.xcconfig: unable to open file (in target "elm" in project "elm") (in target 'elm' from project 'elm')
error: /Users/inkcrazy/Desktop/elmProject/react-native-elm/ios/Pods/Pods/Target Support Files/Pods-elm/Pods-elm.debug.xcconfig: unable to open file (in target "elm" in project "elm") (in target 'elm' from project 'elm')
error: /Users/inkcrazy/Desktop/elmProject/react-native-elm/ios/Pods/Pods/Target Support Files/Pods-elm/Pods-elm.debug.xcconfig: unable to open file (in target "elm" in project "elm") (in target 'elm' from project 'elm')

**Comment by 1280103995** [comment]
iOS运行需要先在根目录下运行 cd ios && pod install && cd ..

README忘记加了
