### ISSUE TITLE
super expression must either be null or a function

### ISSUE THREAD

**Issue by super918180** [1280103995/react-native-elm#5]
![image](https://user-images.githubusercontent.com/20025505/46843980-a699f280-ce07-11e8-83cd-e782633cc7bd.png)

> ## Reproducible Demo
> ```
>export default class ImageView extends Image {
>  constructor(props) {
>    super(props);
>  }
>  render() {
>    ...
>    return super.render();
>  }
>}
> ```

**Comment by 1280103995** [comment]
新版本已经解决了，重新拉取代码吧
